version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: agucova.dev/reguleque
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./phpsrc:/var/www
            - ./infra/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    web:
        image: nginx:alpine
        container_name: web
        restart: unless-stopped
        tty: true
        volumes:
            - ./phpsrc:/var/www
            - ./infra/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8080:80"
        networks:
            - app-network

    database:
        image: mariadb
        container_name: db
        restart: unless-stopped
        networks:
            - app-network
        volumes:
            - dbdata:/var/lib/mysql
            - ./infra/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: reguleque
            MYSQL_ROOT_PASSWORD: reguleque
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql

# Docker Networks
networks:
    app-network:
        driver: bridge
# Volumes
volumes:
    dbdata:
        driver: local
