branch-defaults:
  main:
    environment: regulb-dev
    group_suffix: null
global:
  application_name: regulb
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: PHP 8.0 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
